### ISSUE TITLE
Fails with the current xterm?

### ISSUE THREAD

**Issue by 097115** [pbrisbin/xterm-select-needle#1]
@pbrisbin , this patch looks great but after downloading the latest [xterm source](https://invisible-island.net/datafiles/release/xterm.tar.gz) and applying the patch:

```
patching file ./button.c
Hunk #1 succeeded at 2911 (offset 503 lines).
patching file ./charproc.c
Hunk #1 succeeded at 278 (offset 12 lines).
patching file ./xterm.h
Hunk #1 succeeded at 909 with fuzz 1 (offset 86 lines).
```

`make` breaks for me with the following:

```
gcc -I. -I. -DHAVE_CONFIG_H -D_DEFAULT_SOURCE -D_XOPEN_SOURCE=700 -DNARROWPROTO=1 -DFUNCPROTO=15 -DOSMAJORVERSION=4 -DOSMINORVERSION=15 -DDEFCLASS=\"XTerm\" -DPIXMAP_ROOTDIR=\"$PREFIX/xterm/share/pixmaps/\"   -g -O2  -c ./button.c
./button.c: In function ‘HandleSelectNeedle’:
./button.c:2974:15: error: too few arguments to function ‘ComputeSelect’
               ComputeSelect(xw, &cell, &cell, False);
               ^
./button.c:164:13: note: declared here
 static void ComputeSelect(XtermWidget xw, CELL *startc, CELL *endc, Bool
             ^
Makefile:140: recipe for target 'button.o' failed
make: *** [button.o] Error 1
```

Any hints may be? :)

**Comment by pbrisbin** [comment]
Oh boy, you've found a very old project of mine :)

I'm afraid I can't be of much help here. I wrote this patch mostly as a learning exercise in C and I quickly abandoned it when the resulting functionality didn't totally work. Therefore, I don't use it and I really wouldn't know how to fix it for the latest version.

I'm sorry about that.

**Comment by 097115** [comment]
OK, thanks for the info :)
